# Generated by Django 3.0.2 on 2020-02-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technocrarcApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to='%Y_%d_%m/'),
        ),
    ]
