# Generated by Django 3.0.2 on 2020-02-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technocrarcApp', '0004_effectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectfile',
            name='audio',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='technocrarcApp.AudioFile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to='audio/%Y_%d_%m/'),
        ),
    ]
