# Generated by Django 3.0.3 on 2020-03-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technocrarcApp', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='technocrarcApp.Project'),
            preserve_default=False,
        ),
    ]
