# Generated by Django 3.0.3 on 2020-03-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technocrarcApp', '0007_audiofile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
