name: Django CI

on:
  push:
    branches: [ master, add-ci ]
  pull_request:
    branches: [ master, add-ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/diabled'
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - name: Create DB
      run: |
        mysql -uroot -proot -e "CREATE DATABASE technocrarc;"
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Switch to CI configuration
      run: |
        rm technocrarc/settings.py
        mv technocrarc/settings.py.ci technocrarc/settings.py
    - name: Install Dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py makemigrations
    - name: Run Tests
      run: |
        python manage.py test
  deploy:
    runs-on: ubuntu-latest
    #needs: build
    steps:
    - name: Deploy to SSH SRVZ-WEBAPP
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/app
          rm -rf Technocrarc
          git clone https://github.com/HE-Arc/Technocrarc
          cd Technocrarc
          git checkout ${GITHUB_REF}
          python3 -m venv venv
          source venv/bin/activate
          pip install wheel django
          pip install -r requirements.txt
          python manage.py makemigrations
    
